; Saved by version: 3.15

[MPlaceIronbound1]
xposition=11
yposition=1
master=true

[MPlaceIronbound2]
xposition=10
yposition=2

[MPlaceTheStalker]
xposition=10
yposition=3
master=true

[MPlaceVolucrix1]
xposition=10
yposition=4

[MPlaceVolucrix2]
xposition=10
yposition=2

[MPlaceVolucrix3]
xposition=11
yposition=3

[MPlaceBanditMaster]
xposition=6
yposition=2
master=true

[MPlaceBanditMinion1]
xposition=4
yposition=1

[MPlaceBanditMinion2]
xposition=5
yposition=4

[MPlaceSirAlricFarrow]
xposition=17
yposition=23
master=true

[MPlaceBatteringRam]
xposition=10
yposition=18
master=true

[MPlaceMinionEttin]
xposition=9
yposition=20

[MPlaceShade]
xposition=13
yposition=22
master=true

[MPlaceWildBeast1]
xposition=-2
yposition=3

[MPlaceWildBeast2]
xposition=0
yposition=5
master=true

[MPlaceWildBeast3]
xposition=-2
yposition=5

[MPlaceWildBeast4]
xposition=0
yposition=3

[MPlaceCursed1]
xposition=3
yposition=11
master=true

[MPlaceCursed2]
xposition=0
yposition=10

[MPlaceCursed3]
xposition=2
yposition=9

[MPlaceCursed4]
xposition=2
yposition=12

[MPlaceBanditReinforcment]
xposition=7
yposition=2

[MPlacePalamonBeastmen1]
xposition=8
yposition=18
master=true

[MPlacePalamonBeastmen2]
xposition=7
yposition=16

[MPlacePalamonBeastmen3]
xposition=8
yposition=16

[MPlacePalamonBeastmen4]
xposition=5
yposition=18

[MPlaceSorceror1]
xposition=11
yposition=-1
master=true

[MPlaceSorceror2]
xposition=9
yposition=-1

[MPlaceSorceror3]
xposition=11
yposition=0

[MPlaceSorceror4]
xposition=10
yposition=2

[MPlaceZombie1]
xposition=16
yposition=24
master=true

[MPlaceZombie2]
xposition=18
yposition=24

[MPlaceZombie3]
xposition=16
yposition=23

[MPlaceZombie4]
xposition=14
yposition=24

[MPlaceZombieReinforcement]
xposition=18
yposition=25

[MPlaceShade0]
xposition=12
yposition=23
master=true

[MPlaceShade1]
xposition=13
yposition=21

[MPlaceShade2]
xposition=13
yposition=22

[MPlaceShade3]
xposition=14
yposition=23
