; Saved by version: 3.15
[Quest]
format=20
hidden=False
type=D2E
defaultlanguage=English
defaultmusicon=True
packs=CotF LoR MoR OotO SoE SoN
difficulty=0.75
lengthmin=60
lengthmax=90
image=CastleDaerionImage.png


[QuestText]
Localization.English.txt
Localization.German.txt
Localization.Spanish.txt

[QuestData]
tiles.ini
monsters.ini
spawns.ini
events.ini
tokens.ini
door.ini
mplaces.ini
