; Saved by version: 3.15

[TokenBeacon1]
xposition=11
yposition=-2
buttons=1
event1=EventLightBeacon1
buttoncolor1="yellow"
hero=TokenBeacon1
type=TokenObjectiveRed

[TokenBeacon2]
xposition=7
yposition=5
buttons=1
event1=EventLightBeacon2
buttoncolor1="yellow"
hero=TokenBeacon2
type=TokenObjectiveRed

[TokenBeacon3]
xposition=-2
yposition=2
buttons=1
event1=EventLightBeacon3
buttoncolor1="yellow"
hero=TokenBeacon3
type=TokenObjectiveRed

[TokenBeacon4]
xposition=3
yposition=12
buttons=1
event1=EventLightBeacon4
buttoncolor1="yellow"
hero=TokenBeacon4
type=TokenObjectiveRed

[TokenSearch1]
xposition=10
yposition=-2
buttons=1
event1=EventRemoveSearch1
hero=TokenSearch1
type=TokenSearch

[TokenSearch2]
xposition=6
yposition=0
buttons=1
event1=EventRemoveSearch2
hero=TokenSearch2
type=TokenSearch

[TokenSearch3]
xposition=4
yposition=9
buttons=1
event1=EventRemoveSearch3
hero=TokenSearch3
type=TokenSearch

[TokenSearch4]
xposition=0
yposition=12
buttons=1
event1=EventRemoveSearch4
type=TokenSearch

[TokenSirPalamon]
xposition=14
yposition=17
buttons=2
event1=EventDefeat
buttoncolor1="red"
event2=
buttoncolor2="blue"
hero=TokenSirPalamon
type=TokenObjectiveWhite

[TokenSafePalamon]
xposition=14
yposition=17
buttons=1
event1=EventKeytracker
buttoncolor1="olive"
hero=TokenSafePalamon
type=TokenObjectiveWhite

[TokenSearch5]
xposition=9
yposition=15
buttons=1
event1=EventRemovesearch5
type=TokenSearch

[TokenSearch6]
xposition=16
yposition=22
buttons=1
event1=EventRemoveSearch6
hero=TokenSearch6
type=TokenSearch

[TokenGuard1]
xposition=0
yposition=11
display=false
buttons=0
type=TokenVillagerMan

[TokenGuard6]
xposition=3
yposition=11
display=false
buttons=0
type=TokenVillagerWoman

[TokenGuard2]
xposition=2
yposition=10
display=false
buttons=0
type=TokenVillagerMan

[TokenGuard3]
xposition=1
yposition=11
display=false
buttons=0
type=TokenVillagerWoman

[TokenGuard4]
xposition=1
yposition=12
display=false
buttons=0
type=TokenVillagerMan

[TokenGuard5]
xposition=2
yposition=13
display=false
buttons=0
type=TokenVillagerMan

[TokenGuard7]
xposition=13
yposition=18
display=false
buttons=0
type=TokenVillagerWoman
